const tools=[['مشتریان','♟'],['شارژ','▣'],['دستگاه جدید','▤'],['بازی‌ها','▶'],['تعرفه','▤'],['آمار','▥'],['پرداختی','▰'],['ادمین‌ها','♟'],['تنظیمات','⚙'],['پشتیبان','◫'],['بازیابی','↻'],['فعال‌سازی','▣'],['بروزرسانی','⌕']];
document.getElementById('manager').innerHTML=tools.map(t=>'<button onclick="toolAction(\''+t[0]+'\')"><span class="ico">'+t[1]+'</span>'+t[0]+'</button>').join('');
const pcs=Array.from({length:15},(_,i)=>({id:'PC'+String(i+1).padStart(2,'0'),type:'pc',state:['Active','Idle','Active','Paused','Active','Idle','Active','Active','Banned','Idle','Active','Active','Active','Idle','Active'][i],customer:['Ali R.','','Sina M.','Reza K.','M. Hosseini','','Armin','Nima','','','Amir','Pouya','Hamed','','Soroush'][i],session:['60 min','—','2 hr','90 min','30 min','—','4 hr','60 min','—','—','60 min','30 min','2 hr','—','30 min'][i],remaining:['42:15','—','01:18:44','38:20','21:05','—','02:44:09','16:31','—','—','54:20','12:47','01:06:12','—','07:18'][i],amount:['120,000 تومان','—','240,000 تومان','180,000 تومان','75,000 تومان','—','420,000 تومان','120,000 تومان','—','—','120,000 تومان','75,000 تومان','240,000 تومان','—','75,000 تومان'][i],client:i===9?'Stopped':'Running',security:i===8?'Banned':i===9?'Offline':i===3?'Alarm':'Normal'}));
const ps=[
{id:'PS01',type:'ps',state:'In Use',customer:'Kian',session:'PS5 • 60 min',remaining:'31:22',remainingSeconds:1882,amount:'150,000 تومان',client:'N/A',security:'N/A',timerLabel:'31 min',notice:'Running',timeUp:false,timeWarning:false},
{id:'PS02',type:'ps',state:'Ready',customer:'',session:'PS5',remaining:'—',amount:'—',client:'Online',security:'Normal'},
{id:'PS03',type:'ps',state:'In Use',customer:'Mahan',session:'PS5 • 120 min',remaining:'01:02:18',remainingSeconds:3738,amount:'280,000 تومان',client:'N/A',security:'N/A',timerLabel:'62 min',notice:'Running',timeUp:false,timeWarning:false},
{id:'PS04',type:'ps',state:'Ready',customer:'',session:'PS5',remaining:'—',amount:'—',client:'Online',security:'Normal'},
{id:'PS05',type:'ps',state:'Paused',customer:'Ehsan',session:'PS4 • 60 min',remaining:'18:45',remainingSeconds:1125,amount:'120,000 تومان',client:'N/A',security:'N/A',timerLabel:'19 min',notice:'Running',timeUp:false,timeWarning:false},
{id:'PS06',type:'ps',state:'In Use',customer:'Parsa',session:'PS5 • 60 min',remaining:'09:31',remainingSeconds:571,amount:'150,000 تومان',client:'N/A',security:'N/A',timerLabel:'9 min',notice:'Ending soon',timeUp:false,timeWarning:true}];
const fs=[{id:'FS01',type:'fs',state:'In Use',customer:'Team A',session:'Table • 45 min',remaining:'18:10',remainingSeconds:1090,amount:'90,000 تومان',client:'N/A',security:'N/A',timerLabel:'18 min',notice:'Running',timeUp:false,timeWarning:false},{id:'FS02',type:'fs',state:'Ready',customer:'',session:'Table',remaining:'—',remainingSeconds:0,amount:'—',client:'N/A',security:'N/A',timerLabel:'Ready',notice:'Ready',timeUp:false,timeWarning:false}];
let current='pc',selected=null;
function setType(t,btn){current=t;selected=null;const f=document.getElementById('filter');if(f)f.value='all';document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('selected').textContent='None';render();}
function data(){return current==='pc'?pcs:current==='ps'?ps:fs}
function render(){const f=document.getElementById('filter').value.toLowerCase();let rows=data();if(f!=='all')rows=rows.filter(x=>x.state.toLowerCase()===f);document.getElementById('listTitle').textContent=current==='pc'?'PC Floor':current==='ps'?'PlayStation Floor':'Foosball Floor';document.getElementById('list').innerHTML='<div class="row hdr">'+(current==='pc'?'<span>Unit</span><span>Status</span><span>Customer</span><span>Package</span><span>Time left</span><span>Amount</span><span>Runtime</span><span>Security</span>':'<span>Unit</span><span>Status</span><span>Customer</span><span>Service</span><span>Time left</span><span>Amount</span><span>Timer</span><span>Notice</span>')+'</div>'+rows.map(x=>'<button class="row '+(selected===x.id?'sel':'')+'" onclick="pick(\'\'+x.id+\'\')" ondblclick="openResource(\''+x.id+'\')" oncontextmenu="openContextMenu(event,\''+x.id+'\');return false;"><span class="pcid">'+(x.id)+'</span><span><b class="pill '+x.state.toLowerCase().replace(' ','')+'">'+x.state+'</b></span><span>'+((x.customer)||'—')+'</span><span>'+x.session+'</span><span>'+x.remaining+'</span><span>'+x.amount+'</span><span>'+x.client+'</span><span>'+x.security+'</span></button>').join('')}
function pick(id){selected=id;document.getElementById('selected').textContent=id;const x=data().find(a=>a.id===id);document.getElementById('detail').innerHTML='<div class="detail" onclick="if(event.target===this)closeDetail()"><div class="modal"><button class="close" onclick="closeDetail()">×</button><div class="eyebrow">'+x.id+'</div><h2>'+((x.customer)||'Available')+'</h2><div class="grid2"><div><small>Status</small><b>'+x.state+'</b></div><div><small>Client</small><b>'+x.client+'</b></div><div><small>Session</small><b>'+x.session+'</b></div><div><small>Remaining</small><b>'+x.remaining+'</b></div><div><small>Amount</small><b>'+x.amount+'</b></div><div><small>Security</small><b>'+x.security+'</b></div></div><div class="actions"><button onclick="toggleSelectedPause()">Pause / Resume</button><button onclick="openExtendSelected()">Extend</button><button onclick="toggleSelectedLock()">Force Lock</button><button onclick="logoutSelected()">Force Logout</button><button onclick="toggleSelectedBan()">Ban / Unban</button><button onclick="refreshSelectedRules()">Refresh Rules</button><button onclick="rotateSelectedToken()">Rotate Token</button><button onclick="revokeSelectedCredentials()">Revoke Credentials</button></div></div></div>'}
let _lastDialogTrigger=null;
function escapeHtml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function operationLabel(action){return ({charge:'شارژ اعتبار',free:'اعتبار رایگان',debt:'ثبت بدهی','pay-debt':'پرداخت بدهی',deduct:'کسر اعتبار',discount:'پرداخت + هدیه',vip:'خرید / فعال‌سازی VIP'})[action]||String(action||'عملیات')}
function recordCustomerEvent(event){const item=Object.assign({id:'EV-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),ts:Date.now()},event||{});if(item.sourceOperationId&&previewOperations.some(function(x){return x.sourceOperationId===item.sourceOperationId}))return;previewOperations.unshift(item);if(previewOperations.length>2000)previewOperations.length=2000}
function getCustomerTimeline(customerId){const events=previewOperations.filter(function(x){return x.customerId===customerId});previewPayments.filter(function(x){return x.customerId===customerId}).forEach(function(p){if(!events.some(function(e){return e.paymentId===p.id}))events.push({id:'PAY-EVENT-'+p.id,ts:Date.now(),customerId:customerId,type:'payment',paymentId:p.id,label:p.note,amount:p.amount,method:p.type})});return events.sort(function(a,b){return Number(b.ts||0)-Number(a.ts||0)})}
function ensureControlLabels(root){const labels={filter:'فیلتر وضعیت دستگاه',accountAmount:'مبلغ عملیات حساب',paymentBase:'مبلغ پرداخت مشتری',discountPercent:'درصد هدیه',accountCenterAction:'عملیات حساب',customerSearchPreview:'جستجوی مشتری',hotkeyCustomerInput:'شناسه یا نام مشتری',recoveryFile:'فایل پشتیبان برای بازیابی',assignCustomerSelect:'مشتری برای اتصال به دستگاه',transferTarget:'دستگاه مقصد انتقال Session',extendMinutes:'دقیقه اضافه',vipMonths:'مدت اشتراک VIP',labDevice1:'دستگاه اول Time Pool',labDevice2:'دستگاه دوم Time Pool',labBalance:'موجودی آزمایش Time Pool',licenseKey:'کد فعال‌سازی',rate:'قیمت ساعتی',amount:'مبلغ آزمایشی'};(root||document).querySelectorAll('input,select,textarea').forEach(function(el){if(!el.getAttribute('aria-label')&&!el.getAttribute('aria-labelledby')){const label=labels[el.id];if(label)el.setAttribute('aria-label',label);else if(el.placeholder)el.setAttribute('aria-label',el.placeholder)}})}
function decorateDialog(){const detail=document.getElementById('detail');if(!detail)return;const dlg=detail.querySelector('.modal,.profile,.account-page,.toolbar-page,.tariffbox');if(!dlg)return;dlg.setAttribute('role','dialog');dlg.setAttribute('aria-modal','true');const h=dlg.querySelector('h1,h2,h3');if(h){if(!h.id)h.id='dialog-title-'+Date.now().toString(36);dlg.setAttribute('aria-labelledby',h.id)}ensureControlLabels(dlg);const f=[...dlg.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')];if(f.length&&!dlg.contains(document.activeElement))f[0].focus()}
function installAccessibilityFoundation(){const toast=document.getElementById('toast');if(toast){toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');toast.setAttribute('aria-atomic','true')}document.addEventListener('click',function(e){const t=e.target.closest('button,a,[role="button"]');if(t&&!t.closest('#detail'))_lastDialogTrigger=t},true);document.addEventListener('keydown',function(e){const dlg=document.getElementById('detail')?.querySelector('[role="dialog"]');if(e.key==='Escape'&&dlg){e.preventDefault();closeDetail();return}if(dlg&&e.key==='Tab'){const f=[...dlg.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')];if(f.length){const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}});const obs=new MutationObserver(function(m){if(m.some(function(x){return x.type==='childList'}))setTimeout(function(){decorateDialog();ensureControlLabels(document);document.querySelectorAll('.customer-table,.toolbar-table').forEach(function(t){if(!t.getAttribute('role'))t.setAttribute('role','table');t.querySelectorAll('.customer-table-row,.toolbar-row').forEach(function(row){if(!row.getAttribute('role'))row.setAttribute('role','row')})})},0)});obs.observe(document.getElementById('detail'),{childList:true,subtree:true})}
function closeDetail(){document.getElementById('detail').innerHTML='';const t=_lastDialogTrigger;setTimeout(function(){if(t&&document.contains(t))t.focus()},0)}
function profileFor(x){
  const live=previewCustomers&&previewCustomers.find(function(c){return c.id===x?.customerId||c.id===x?.customer||c.name===x?.customer});
  if(live){const active=Array.isArray(live.activeSessions)?live.activeSessions:[],first=active[0]?.deviceId||live.unit||x?.id||'—',u=calculateSharedUsage(live),time=active.length?formatSharedTime(u.remainingSeconds):((x&&x.session)||'—');return [live.name,live.id,live.phone,(Number(live.balance||0)).toLocaleString()+' تومان',live.vipActive?(live.vip||'VIP'):'ندارد',first,(active.length?active.length+' اتصال • '+time:(x&&x.session)||'—')];}
  const map={'Ali R.':['Ali R.','1040','0912***21','120,000 تومان','تا 1405/07/20','PC01','60 min • 42:15'],'Sina M.':['Sina M.','1041','0919***14','240,000 تومان','ندارد','PC03','2 hr • 01:18:44'],'Reza K.':['Reza K.','1042','0935***08','0 تومان','ندارد','PC04','90 min • 38:20'],'Armin':['Armin','1043','0910***42','580,000 تومان','VIP','PC07','4 hr • 02:44:09'],'Nima':['Nima','1044','0911***11','85,000 تومان','ندارد','PC08','60 min • 16:31'],'Amir':['Amir','1045','0902***55','45,000 تومان','ندارد','PC11','60 min • 54:20'],'Pouya':['Pouya','1046','0913***66','15,000 تومان','ندارد','PC12','30 min • 12:47'],'Hamed':['Hamed','1047','0930***44','210,000 تومان','VIP','PC13','2 hr • 01:06:12'],'Soroush':['Soroush','1048','0918***77','50,000 تومان','ندارد','PC15','30 min • 07:18'],'Kian':['Kian','2050','0919***33','70,000 تومان','VIP','PS01','PS5 • 31:22'],'Mahan':['Mahan','2051','0936***12','10,000 تومان','ندارد','PS03','PS5 • 01:02:18'],'Ehsan':['Ehsan','2052','0912***10','0 تومان','ندارد','PS05','PS4 • 18:45'],'Parsa':['Parsa','2053','0915***24','35,000 تومان','ندارد','PS06','PS5 • 09:31'],'Team A':['Team A','3001','—','—','—','FS01','Table • 18:10']};return map[x?.customer];
}
