function openCustomerManager(){
  document.getElementById('detail').innerHTML=`<div class="detail" style="align-items:center"><div class="customer-page"><div class="head"><div><div class="eyebrow">Customer Management</div><h2 style="margin:2px 0;font-size:15px">مشتریان</h2><p style="margin:0;font-size:9px;color:#8a95a5">ساخت مشتری، جستجو و بازکردن پروفایل حسابی</p></div><div class="ctx"><input id="customerSearchPreview" class="customer-search" placeholder="جستجو..."><button class="primary" onclick="openCreateCustomer()">＋ مشتری جدید</button><button onclick="closeDetail()">بستن</button></div></div><div class="permission-lock">🔒 عملیات مالی و VIP فقط طبق Permission ادمین/شاگرد</div><div class="customer-table"><div class="customer-table-row customer-table-head"><span>مشتری</span><span>کد / کاربری</span><span>تلفن</span><span>اعتبار</span><span>بدهی</span><span>VIP</span><span>دستگاه</span><span>عملیات</span></div><div id="customerRowsPreview"></div></div></div></div>`;
  renderCustomerRows();
  document.getElementById('customerSearchPreview').addEventListener('input',renderCustomerRows);
}
function renderCustomerRows(){
  const q=(document.getElementById('customerSearchPreview')?.value||'').toLowerCase();
  const rows=previewCustomers.filter(function(x){return !q||[x.id,x.name,x.username,x.phone].some(function(v){return String(v||'').toLowerCase().includes(q)})});
  document.getElementById('customerRowsPreview').innerHTML=rows.map(function(x){
    const xid=escapeHtml(x.id),name=escapeHtml(x.name),last=escapeHtml(x.lastVisit),user=escapeHtml(x.username),phone=escapeHtml(x.phone),vip=x.vipActive?escapeHtml(x.vip)+' • تا '+escapeHtml(x.vipExpiry):'—',unit=escapeHtml(x.unit);
    return '<div class="customer-table-row" ondblclick="openCustomerRecordPreview(\''+xid+'\')"><span><strong>'+name+'</strong><small style="display:block;color:#929cab">'+last+'</small></span><span>#'+xid+' / '+user+'</span><span>'+phone+'</span><span class="money-positive">'+Number(x.balance||0).toLocaleString()+' تومان</span><span class="'+(x.debt>0?'money-danger':'')+'">'+Number(x.debt||0).toLocaleString()+' تومان</span><span>'+vip+'</span><span>'+unit+'</span><span class="customer-row-btn"><button class="mini-action" onclick="openCustomerRecordPreview(\''+xid+'\')">پروفایل</button></span></div>'
  }).join('')||'<div style="padding:20px;text-align:center;font-size:9px;color:#6d7788">مشتری پیدا نشد</div>';
}
function openCreateCustomer(){
  document.getElementById('detail').innerHTML=`<div class="detail" onclick="if(event.target===this)openCustomerManager()"><div class="modal create-customer-modal"><button class="close" onclick="openCustomerManager()">×</button><div class="eyebrow">Customer creation</div><h2>ایجاد مشتری تستی</h2><div class="grid2"><div><small>نام مشتری</small><input id="newCName" style="width:100%;height:30px" value="مشتری تستی"></div><div><small>کد مشتری</small><input id="newCId" style="width:100%;height:30px" value="1050"></div><div><small>نام کاربری</small><input id="newCUser" style="width:100%;height:30px" value="test.customer"></div><div><small>رمز / PIN</small><input id="newCPin" style="width:100%;height:30px" value="1234"></div><div><small>شماره موبایل</small><input id="newCPhone" style="width:100%;height:30px" value="09120000000"></div><div><small>اعتبار اولیه</small><input id="newCBalance" type="number" style="width:100%;height:30px" value="100000"></div></div><div class="detail-alert">این مشتری برای تست UI ساخته می‌شود و بعد می‌توانی دوبارکلیک کنی و همان پروفایل حسابی را ببینی.</div><div class="actions"><button onclick="openCustomerManager()">انصراف</button><button class="primary" onclick="createPreviewCustomer()">ایجاد مشتری</button></div></div></div>`;
}
function createPreviewCustomer(){
  const id=String(document.getElementById('newCId')?.value||String(1050+previewCustomers.length)).trim(),name=String(document.getElementById('newCName')?.value||'مشتری تستی').trim(),username=String(document.getElementById('newCUser')?.value||'test.customer').trim(),phone=String(document.getElementById('newCPhone')?.value||'—').trim(),pin=String(document.getElementById('newCPin')?.value||'1234').trim(),balance=Math.max(0,Number(document.getElementById('newCBalance')?.value||0));
  if(!id||!name||!username){showToast('شناسه، نام و نام کاربری الزامی است');return}
  if(previewCustomers.some(function(x){return x.id===id})){showToast('این شناسه قبلاً استفاده شده است');return}
  if(previewCustomers.some(function(x){return String(x.username||'').toLowerCase()===username.toLowerCase()})){showToast('این نام کاربری قبلاً استفاده شده است');return}
  const cc={id:id,name:name,username:username,pin:pin,phone:phone,balance:balance,freeCredit:0,debt:0,vip:'—',vipActive:false,vipExpiry:'—',unit:'—',lastVisit:'همین حالا',maxConcurrent:1,sharedTimePool:true,activeSessions:[]};
  previewCustomers.unshift(cc);recordCustomerEvent({customerId:cc.id,type:'customer-create',label:'ساخت مشتری'});persistAppState('customer-create');showToast('مشتری ساخته شد: #'+cc.id+' • '+cc.username);openCustomerManager();
}

function openCustomerRecordPreview(id){const x=previewCustomers.find(v=>v.id===id);if(!x)return;const resource={id:x.unit==='—'?'CUSTOMER'+x.id:x.unit,type:'pc',state:x.unit==='—'?'Idle':'Active',customer:x.name,session:x.unit==='—'?'—':'Session',remaining:'—',amount:x.balance.toLocaleString()};openProfile(resource)}
function openStaffManager(){
  document.getElementById('detail').innerHTML=`<div class="detail" style="align-items:center"><div class="customer-page"><div class="head"><div><div class="eyebrow">Owner Controls</div><h2 style="margin:2px 0;font-size:15px">ادمین‌ها و شاگردها</h2><p style="margin:0;font-size:9px;color:#8a95a5">مالک اصلی تعیین می‌کند هر شاگرد به چه بخش و چه عملیات مشتری دسترسی داشته باشد.</p></div><div class="ctx"><button class="primary" onclick="openCreateStaff()">＋ شاگرد / ادمین جدید</button><button onclick="closeDetail()">بستن</button></div></div><div class="permission-lock">🔒 فقط Owner می‌تواند Permissionها را تغییر دهد</div><div class="customer-table"><div class="customer-table-row customer-table-head staff-grid"><span>کاربر</span><span>نقش</span><span>شعبه</span><span>دسترسی برنامه</span><span>پروفایل مشتری</span><span>وضعیت</span><span>عملیات</span></div><div id="staffRowsPreview"></div></div></div></div>`;
  document.getElementById('staffRowsPreview').innerHTML=previewStaff.map(function(x,i){
    return '<div class="customer-table-row staff-grid"><span><strong>'+escapeHtml(x.name)+'</strong><small style="display:block;color:#929cab">'+escapeHtml(x.username)+'</small></span><span>'+escapeHtml(x.role)+'</span><span>'+escapeHtml(x.branch)+'</span><span>'+escapeHtml(formatPermissionList(x.permissions,previewPermissions))+'</span><span>'+escapeHtml(formatPermissionList(x.customerPermissions,previewCustomerPermissions))+'</span><span>Active</span><span><button class="mini-action" '+(x.role==='Owner'?'disabled aria-disabled="true"':'')+' onclick="openStaffPermissions('+i+')">دسترسی</button></span></div>'
  }).join('');
}
function openCreateStaff(){openStaffEditor({name:'',username:'',role:'Operator',branch:'Main',permissions:[],customerPermissions:[]},-1)}
function formatPermissionList(value,map){const arr=Array.isArray(value)?value:[];if(arr.length>=map.length)return 'همه';return arr.map(function(k){const hit=map.find(function(p){return p[0]===k});return hit?hit[1]:k}).join(' + ')||'بدون دسترسی'}
function openStaffPermissions(index){const x=previewStaff[index];openStaffEditor({...x,permissions:Array.isArray(x.permissions)?x.permissions.slice():[],customerPermissions:Array.isArray(x.customerPermissions)?x.customerPermissions.slice():[]},index)}
function openStaffEditor(staff,index){
  const perms=Array.isArray(staff.permissions)?staff.permissions:[], cps=Array.isArray(staff.customerPermissions)?staff.customerPermissions:[];
  document.getElementById('detail').innerHTML=`<div class="detail"><div class="profile permissions-modal" role="dialog" aria-modal="true"><button class="close" aria-label="بستن" onclick="openStaffManager()">×</button><div class="eyebrow">Owner only</div><h2>${index<0?'ساخت پروفایل شاگرد / ادمین':'تنظیم دسترسی '+escapeHtml(staff.name)}</h2><div class="grid2"><div><small>نام</small><input id="staffName" value="${escapeHtml(staff.name)}" style="width:100%;height:30px"></div><div><small>نام کاربری</small><input id="staffUser" value="${escapeHtml(staff.username)}" style="width:100%;height:30px"></div><div><small>نقش</small><select id="staffRole" style="width:100%;height:30px"><option ${staff.role==='Operator'?'selected':''}>Operator</option><option ${staff.role==='Branch Admin'?'selected':''}>Branch Admin</option></select></div><div><small>شعبه</small><select id="staffBranch" style="width:100%;height:30px"><option>Main</option><option>Branch 2</option><option>Branch 3</option></select></div></div><div class="permission-editor"><strong>دسترسی بخش‌های برنامه</strong><div id="programPerms"></div></div><div class="permission-editor"><strong>دسترسی عملیات پروفایل مشتری</strong><div id="customerPerms"></div></div><div class="detail-alert">مالک اصلی می‌تواند هر مورد را انتخاب کند. در Production این Permissionها باید Server-side enforce و Audit شوند.</div><div class="actions"><button onclick="openStaffManager()">انصراف</button><button class="primary" onclick="savePreviewStaff(${index})">ذخیره</button></div></div></div>`;
  document.getElementById('programPerms').innerHTML=previewPermissions.map(([k,l])=>`<label class="permission-check"><input type="checkbox" value="${k}" ${perms.includes(k)?'checked':''}> ${l}</label>`).join('');
  document.getElementById('customerPerms').innerHTML=previewCustomerPermissions.map(([k,l])=>`<label class="permission-check"><input type="checkbox" value="${k}" ${cps.includes(k)?'checked':''}> ${l}</label>`).join('');
}
function savePreviewStaff(index){
  const rec={name:document.getElementById('staffName').value,username:document.getElementById('staffUser').value,role:document.getElementById('staffRole').value,branch:document.getElementById('staffBranch').value,permissions:[...document.querySelectorAll('#programPerms input:checked')].map(x=>x.value),customerPermissions:[...document.querySelectorAll('#customerPerms input:checked')].map(x=>x.value)};
  rec.customerProfile=formatPermissionList(rec.customerPermissions,previewCustomerPermissions);
  if(index<0)previewStaff.push(rec);else previewStaff[index]=rec;
  persistAppState('staff');
  showToast('پروفایل شاگرد و Permissionها ذخیره شد');
  openStaffManager();
}
