function openResource(id){const x=data().find(a=>a.id===id);if(!x)return;selected=id;document.getElementById('selected').textContent=id;if(x.customer){openProfile(x)}else{openDeviceSettings(id)}}

function getSelectedResource(){return selected?getDeviceById(selected):null}
function syncCustomerDeviceViews(cc){if(!cc)return;const u=calculateSharedUsage(cc);(cc.activeSessions||[]).forEach(function(s){const d=getDeviceById(s.deviceId);if(d){d.remainingSeconds=u.remainingSeconds;d.remaining=formatSharedTime(u.remainingSeconds);d.timerLabel=u.remainingSeconds<=0?'00:00':Math.ceil(u.remainingSeconds/60)+' min';d.timeWarning=u.remainingSeconds<=600&&u.remainingSeconds>0;d.timeUp=u.remainingSeconds<=0;d.notice=s.paused?'Paused':(d.timeUp?'TIME UP':d.timeWarning?'Ending soon':'Running');if(!s.paused&&!d.locked)d.state=d.type==='pc'?'Active':'In Use'}})}
function newSelectedSession(){const d=getSelectedResource();if(!d){const first=data()[0];if(!first){showToast('دستگاهی برای شروع Session وجود ندارد');return}pick(first.id);return}if(d.customer){openProfile(d);return}openAssignCustomer(d.id)}
function startSelectedSession(){const d=getSelectedResource();if(!d){showToast('ابتدا یک دستگاه انتخاب کن');return}if(d.customer){const cc=previewCustomers.find(function(x){return x.name===d.customer});const ss=cc?.activeSessions.find(function(s){return s.deviceId===d.id});if(ss?.paused){ss.paused=false;d.locked=false;d.state=d.type==='pc'?'Active':'In Use';recordCustomerEvent({customerId:cc.id,type:'session-toggle',label:'ادامه Session',deviceId:d.id});syncCustomerDeviceViews(cc);persistAppState('session-resume');showToast(d.id+' ادامه یافت');render();return}showToast(d.id+' در حال اجراست');return}openAssignCustomer(d.id)}
function toggleSelectedPause(){const d=getSelectedResource();if(!d?.customer){showToast('برای این دستگاه Session فعالی وجود ندارد');return}const cc=previewCustomers.find(function(x){return x.name===d.customer}),ss=cc?.activeSessions.find(function(s){return s.deviceId===d.id});if(!cc||!ss)return;ss.paused=!ss.paused;d.state=ss.paused?'Paused':(d.type==='pc'?'Active':'In Use');d.notice=ss.paused?'Paused':'Running';recordCustomerEvent({customerId:cc.id,type:'session-toggle',label:ss.paused?'توقف Session':'ادامه Session',deviceId:d.id});persistAppState(ss.paused?'session-pause':'session-resume');showToast(ss.paused?d.id+' متوقف شد':d.id+' ادامه یافت');render()}
function openTransferSelected(){const d=getSelectedResource();if(!d?.customer){showToast('ابتدا یک Session فعال انتخاب کن');return}openTransferSession(d.id)}
function openTransferSession(fromId){const from=getDeviceById(fromId),cc=previewCustomers.find(function(x){return x.activeSessions.some(function(s){return s.deviceId===fromId})});if(!from||!cc)return;const candidates=[...pcs,...ps,...fs].filter(function(d){return d.id!==fromId&&d.type===from.type&&!d.customer&&!d.locked});const opts=candidates.map(function(d){return '<option value="'+d.id+'">'+d.id+' • '+(getDeviceTariff(d.id)==='vip'?'VIP':'عادی')+' • '+getDeviceRate(d.id).toLocaleString()+' تومان/ساعت</option>'}).join('')||'<option value="">دستگاه خالی موجود نیست</option>';toolbarModal('انتقال Session','<div class="detail-alert">'+cc.name+' • '+from.id+' → دستگاهی از همان نوع. Time Pool مشترک باقی می‌ماند.</div><select id="transferTarget" class="toolbar-select">'+opts+'</select><div class="actions"><button onclick="toolbarClose()">انصراف</button><button class="primary" onclick="applyTransferSession(\''+fromId+'\')">انتقال</button></div>',500)}
function applyTransferSession(fromId){const toId=document.getElementById('transferTarget')?.value,from=getDeviceById(fromId),to=getDeviceById(toId),cc=previewCustomers.find(function(x){return x.activeSessions.some(function(s){return s.deviceId===fromId})});if(!toId||!from||!to||!cc)return;if(to.customer||to.locked){showToast('دستگاه مقصد آزاد نیست');return}const ss=cc.activeSessions.find(function(s){return s.deviceId===fromId});if(!ss)return;ss.deviceId=toId;from.customer='';from.state=from.type==='pc'?'Idle':'Ready';from.session=from.type==='pc'?'—':from.type==='ps'?'PS5':'Table';from.remaining='—';from.remainingSeconds=0;from.notice='Ready';to.customer=cc.name;to.locked=false;to.state=ss.paused?'Paused':(to.type==='pc'?'Active':'In Use');to.session=to.type==='pc'?'Session':to.type==='ps'?'PS5 • Session':'Table • Session';to.client=to.type==='pc'?'Running':'N/A';to.security=to.type==='pc'?'Normal':'N/A';syncCustomerDeviceViews(cc);persistAppState('session-transfer');toolbarClose();openCustomerRecordPreview(cc.id);showToast(fromId+' به '+toId+' منتقل شد')}
function openExtendSelected(){const d=getSelectedResource();if(!d?.customer){showToast('Session فعالی برای افزایش زمان وجود ندارد');return}const cc=previewCustomers.find(function(x){return x.name===d.customer});const rate=getDeviceRate(d.id);toolbarModal('افزایش زمان','<div class="detail-alert">زمان اضافه به Time Pool مشترک '+cc.name+' اضافه می‌شود و در همه Sessionهای فعال این مشتری قابل مصرف است.</div><label style="font-size:9px">دقیقه اضافه<input id="extendMinutes" class="toolbar-input" type="number" min="1" step="5" value="30"></label><div class="lab-result" id="extendPreview"></div><div class="actions"><button onclick="toolbarClose()">انصراف</button><button class="primary" onclick="applyExtendSelected(\''+d.id+'\')">ثبت زمان</button></div>',500);setTimeout(function(){const el=document.getElementById('extendMinutes');el?.addEventListener('input',updateExtendPreview);updateExtendPreview()},10);window._extendContext={customerId:cc.id,rate:rate}}
function updateExtendPreview(){const m=Math.max(0,Number(document.getElementById('extendMinutes')?.value||0)),ctx=window._extendContext,el=document.getElementById('extendPreview');if(el)el.innerHTML='<div class="lab-lines"><div><span>دقیقه</span><strong>'+m.toLocaleString('fa-IR')+'</strong></div><div><span>اعتبار رایگان افزوده</span><strong>'+Math.round((ctx?.rate||0)*m/60).toLocaleString()+' تومان</strong></div><div><span>تقریب زمان</span><strong>'+formatSharedTime(m*60)+'</strong></div></div>'}
function applyExtendSelected(deviceId){const ctx=window._extendContext,cc=previewCustomers.find(function(x){return x.id===ctx?.customerId}),m=Math.max(0,Number(document.getElementById('extendMinutes')?.value||0)),amount=Math.round((ctx?.rate||getDeviceRate(deviceId))*m/60);if(!cc||m<=0||amount<=0){showToast('مدت اضافه نامعتبر است');return}if(!commitAccountOperation({action:'free',customerId:cc.id,amount:amount,source:'manual-extend',minutes:m,deviceId:deviceId})){return}delete window._extendContext;toolbarClose();openCustomerRecordPreview(cc.id);showToast(m+' دقیقه به Time Pool مشتری اضافه شد')}
function toggleSelectedLock(){const d=getSelectedResource();if(!d){showToast('ابتدا یک دستگاه انتخاب کن');return}const cc=previewCustomers.find(function(x){return x.activeSessions.some(function(s){return s.deviceId===d.id})}),ss=cc?.activeSessions.find(function(s){return s.deviceId===d.id});if(d.locked){d.locked=false;if(ss)ss.paused=false;d.state=cc?(d.type==='pc'?'Active':'In Use'):(d.type==='pc'?'Idle':'Ready');d.notice=cc?'Running':'Ready';persistAppState('unlock-device');showToast(d.id+' از حالت قفل خارج شد')}else{d.locked=true;if(ss)ss.paused=true;d.state='Locked';d.notice='Locked';persistAppState('lock-device');showToast(d.id+' قفل شد')}render()}
function logoutSelected(){const d=getSelectedResource();if(!d?.customer){showToast('Session فعالی وجود ندارد');return}const cc=previewCustomers.find(function(x){return x.activeSessions.some(function(s){return s.deviceId===d.id})});if(!cc)return;recordCustomerEvent({customerId:cc.id,type:'session-stop',label:'خروج Session',deviceId:d.id});removeCustomerSession(cc.id,d.id);persistAppState('session-logout');render();showToast('Session '+d.id+' بسته شد')}
function toggleSelectedBan(){const d=getSelectedResource();if(!d)return;d.banned=!d.banned;const cc=previewCustomers.find(function(x){return x.activeSessions.some(function(s){return s.deviceId===d.id})}),ss=cc?.activeSessions.find(function(s){return s.deviceId===d.id});if(d.banned){if(ss)ss.paused=true;d.state='Banned';d.notice='Banned';recordCustomerEvent({customerId:cc?.id,type:'device-ban',label:'مسدودسازی دستگاه',deviceId:d.id})}else{if(ss)ss.paused=false;d.state=cc?(d.type==='pc'?'Active':'In Use'):(d.type==='pc'?'Idle':'Ready');d.notice=cc?'Running':'Ready';recordCustomerEvent({customerId:cc?.id,type:'device-unban',label:'رفع انسداد دستگاه',deviceId:d.id})}persistAppState('ban-toggle');showToast(d.id+(d.banned?' مسدود شد':'از انسداد خارج شد'));render();}
function refreshSelectedRules(){const d=getSelectedResource();if(!d)return;d.rulesVersion=(Number(d.rulesVersion||0)+1);persistAppState('rules-refresh');showToast('قوانین '+d.id+' دوباره اعمال شد')}
function rotateSelectedToken(){const d=getSelectedResource();if(!d)return;d.tokenVersion=(Number(d.tokenVersion||0)+1);persistAppState('token-rotate');showToast('Token '+d.id+' چرخانده شد')}
function revokeSelectedCredentials(){const d=getSelectedResource();if(!d)return;d.credentialsRevoked=!d.credentialsRevoked;persistAppState('credentials');showToast(d.credentialsRevoked?'اعتبارنامه '+d.id+' باطل شد':'اعتبارنامه '+d.id+' فعال شد')}
function openPreviewAlerts(){toolbarModal('هشدارها','<div class="account-list"><div class="account-row"><div class="account-row-label"><strong>جلسه نیازمند توجه</strong><small>PC04 • Heartbeat بازیابی شد</small></div><span class="notice warn">بررسی</span><button class="account-action" onclick="showToast(\'هشدار PC04 بررسی شد\')">تأیید</button></div><div class="account-row"><div class="account-row-label"><strong>تنظیمات شبکه</strong><small>۲ هشدار نمایشی در محیط Preview</small></div><span class="notice">Info</span><button class="account-action" onclick="showToast(\'هشدار نمایشی بسته شد\')">بستن</button></div></div><div class="actions"><button onclick="toolbarClose()">بستن</button></div>',620)}
function selectFirst(){const x=data()[0];if(x)pick(x.id)}
function showPage(title){document.getElementById('title').textContent=title}
function formatRateTime(rate,amount){rate=Number(rate||0);amount=Number(amount||0);if(rate<=0||amount<=0)return'—';const sec=Math.floor(amount/rate*3600),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?String(h)+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0'):String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
