function openChargeManager(){openHotkeyCustomerSearch('accountCenter')}
function updateChargeManagerPreview(){const cc=previewCustomers.find(function(x){return x.id===document.getElementById('chargeCustomerSelect')?.value}),p=Number(document.getElementById('chargeManagerAmount')?.value||0),pct=Math.max(0,Math.min(100,Number(document.getElementById('chargeManagerBonus')?.value||0))),free=Math.round(p*pct/100),total=p+free,rate=cc?getCustomerEffectiveRate({customerId:cc.id}):previewPricing.normal.pc,el=document.getElementById('chargeManagerPreview');if(el)el.innerHTML='<div class="lab-lines"><div><span>پرداختی</span><strong>'+p.toLocaleString()+' تومان</strong></div><div><span>رایگان</span><strong>'+free.toLocaleString()+' تومان</strong></div><div><span>ارزش کل</span><strong>'+total.toLocaleString()+' تومان • '+formatSharedTime(rate?Math.floor(total/rate*3600):0)+'</strong></div></div>'}
function openDeviceManager(){showPage('PC Management');const rows=[...pcs,...ps,...fs].map(function(d){const cls=getDeviceTariff(d.id),rate=getDeviceRate(d.id);return '<div class="toolbar-row"><span><b>'+d.id+'</b></span><span>'+d.type.toUpperCase()+'</span><span>'+(d.customer||'آزاد')+'</span><span class="device-class-toggle"><button class="mini-action '+(cls==='normal'?'device-class-active':'')+'" onclick="setDeviceTariffClass(\''+d.id+'\',\'normal\')">عادی</button><button class="mini-action '+(cls==='vip'?'device-class-active vip':'')+'" onclick="setDeviceTariffClass(\''+d.id+'\',\'vip\')">VIP</button></span><span><b>'+rate.toLocaleString()+' تومان/ساعت</b><small class="device-rate-source">طبق تعرفه</small></span><span><button class="mini-action" onclick="openAssignCustomer(\''+d.id+'\')">جلسه</button> <button class="mini-action" onclick="openDeviceSettings(\''+d.id+'\')">تنظیم</button></span></div>'}).join('');document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page"><button class="close" onclick="closeDetail()">×</button><div class="head"><div><div class="eyebrow">Device management</div><h2>دستگاه‌ها و کلاس تعرفه</h2><p class="toolbar-sub">اینجا فقط کلاس هر سیستم را انتخاب می‌کنی؛ قیمت همیشه از «تعرفه‌ها» خوانده می‌شود.</p></div><div class="toolbar-actions"><button class="primary" onclick="openCreateDevice()">＋ دستگاه جدید</button><button onclick="openSharedTimeLab()">آزمایش همزمان</button></div></div><div class="detail-alert">قیمت دستی برای هر سیستم وجود ندارد. انتخاب «VIP» یا «عادی» بلافاصله نرخ متناظر PC / PS / Foosball را از تعرفه اعمال می‌کند.</div><div class="toolbar-table"><div class="toolbar-row toolbar-head"><span>شناسه</span><span>نوع</span><span>مشتری</span><span>کلاس تعرفه</span><span>نرخ اعمال‌شده</span><span>عملیات</span></div>'+rows+'</div></div></div>'}
function setDeviceTariffClass(id,cls){deviceTariffClass[id]=cls==='vip'?'vip':'normal';persistAppState('device-tariff');showToast(id+' روی '+(deviceTariffClass[id]==='vip'?'VIP':'عادی')+' تنظیم شد');openDeviceManager()}
function setDeviceTariffClassFromModal(id,cls){
  const d=getDeviceById(id);
  if(!d)return;
  window._pendingDeviceTariff={id:id,cls:cls==='vip'?'vip':'normal'};
  openDeviceSettings(id);
  showToast(id+' • کلاس '+(window._pendingDeviceTariff.cls==='vip'?'VIP':'عادی')+' انتخاب شد؛ برای ذخیره «تأیید» را بزن.');
}
function cancelDeviceSettings(){
  delete window._pendingDeviceTariff;
  openDeviceManager();
}
function saveDeviceSettings(){
  const pending=window._pendingDeviceTariff;
  if(!pending||!getDeviceById(pending.id)){showToast('تنظیم دستگاه پیدا نشد');return}
  deviceTariffClass[pending.id]=pending.cls==='vip'?'vip':'normal';
  persistAppState('device-tariff');
  delete window._pendingDeviceTariff;
  showToast(pending.id+' روی '+(deviceTariffClass[pending.id]==='vip'?'VIP':'عادی')+' ذخیره شد');
  openDeviceManager();
}
function openDeviceSettings(id){
  const d=getDeviceById(id);
  if(!d){showToast('دستگاه پیدا نشد');return}
  const current=getDeviceTariff(id);
  const pending=window._pendingDeviceTariff&&window._pendingDeviceTariff.id===id?window._pendingDeviceTariff.cls:current;
  const rate=getDeviceRate(id);
  const shownRate=Number(previewPricing[pending]?.[d.type]||previewPricing.normal[d.type]||0);
  document.getElementById('detail').innerHTML='<div class="detail" onclick="if(event.target===this)cancelDeviceSettings()"><div class="modal" role="dialog" aria-modal="true" style="width:480px"><button class="close" aria-label="بازگشت" onclick="cancelDeviceSettings()">×</button><div class="eyebrow">Device settings</div><h2>تنظیم '+escapeHtml(d.id)+'</h2><div class="grid2"><div><small>شناسه</small><b>'+escapeHtml(d.id)+'</b></div><div><small>نوع</small><b>'+escapeHtml(d.type.toUpperCase())+'</b></div><div class="device-class-setting"><small>کلاس تعرفه</small><div class="device-class-toggle"><button type="button" class="mini-action '+(pending==='normal'?'device-class-active':'')+'" onclick="setDeviceTariffClassFromModal(\''+escapeHtml(d.id)+'\',\'normal\')">عادی</button><button type="button" class="mini-action '+(pending==='vip'?'device-class-active vip':'')+'" onclick="setDeviceTariffClassFromModal(\''+escapeHtml(d.id)+'\',\'vip\')">VIP</button></div></div><div><small>نرخ قابل اعمال</small><b>'+shownRate.toLocaleString()+' تومان/ساعت</b><small class="device-rate-source">قیمت از بخش «تعرفه‌ها» خوانده می‌شود.</small></div></div><div class="detail-alert">کلاس انتخاب‌شده: <b>'+(pending==='vip'?'VIP':'عادی')+'</b> • نرخ: <b>'+shownRate.toLocaleString()+' تومان/ساعت</b></div><div class="actions"><button type="button" onclick="cancelDeviceSettings()">بازگشت</button><button type="button" class="primary" onclick="saveDeviceSettings()">✓ تأیید و ذخیره</button></div></div></div>';
}
function openAssignCustomer(deviceId){const opts=previewCustomers.map(function(cc){return '<option value="'+cc.id+'">'+cc.id+' • '+cc.name+' • '+cc.activeSessions.length+' اتصال</option>'}).join('');toolbarModal('اتصال مشتری به '+deviceId,'<div class="detail-alert">چند Session یک مشتری از یک Time Pool مشترک کم می‌شوند.</div><select id="assignCustomerSelect" class="toolbar-select">'+opts+'</select><div id="assignPreview" class="lab-result"></div><div class="actions"><button onclick="toolbarClose()">انصراف</button><button onclick="stopAssignedCustomer(\''+deviceId+'\')">توقف</button><button class="primary" onclick="applyAssignedCustomer(\''+deviceId+'\')">شروع</button></div>',560);setTimeout(function(){document.getElementById('assignCustomerSelect')?.addEventListener('change',updateAssignPreview);updateAssignPreview()},10)}
function updateAssignPreview(){const cc=previewCustomers.find(function(x){return x.id===document.getElementById('assignCustomerSelect')?.value}),u=cc?calculateSharedUsage(cc):{active:[],totalRate:0,remainingSeconds:0},el=document.getElementById('assignPreview');if(cc&&el)el.innerHTML='<div class="lab-lines"><div><span>فعلی</span><strong>'+(u.active.map(function(s){return s.deviceId}).join(' + ')||'—')+'</strong></div><div><span>نرخ</span><strong>'+u.totalRate.toLocaleString()+' تومان/ساعت</strong></div><div><span>زمان</span><strong>'+formatSharedTime(u.remainingSeconds)+'</strong></div></div>'}
function applyAssignedCustomer(deviceId){const id=document.getElementById('assignCustomerSelect')?.value;if(!id||!startPreviewSession(id,deviceId))return;const cc=previewCustomers.find(function(x){return x.id===id});toolbarClose();openCustomerRecordPreview(cc.id);showToast(getSharedTimeSummary(cc))}
function stopAssignedCustomer(deviceId){const cc=previewCustomers.find(function(x){return x.activeSessions.some(function(s){return s.deviceId===deviceId})});if(cc){removeCustomerSession(cc.id,deviceId);persistAppState('session-stop')}toolbarClose();openDeviceManager()}
function openCreateDevice(){toolbarModal('افزودن دستگاه','<div class="grid2"><div><small>شناسه</small><input id="newDeviceId" class="toolbar-input" value="PC16"></div><div><small>نوع</small><select id="newDeviceType" class="toolbar-select"><option value="pc">PC</option><option value="ps">PS</option><option value="fs">Foosball</option></select></div><div><small>کلاس</small><select id="newDeviceClass" class="toolbar-select"><option value="normal">عادی</option><option value="vip">VIP</option></select></div></div><div class="actions"><button onclick="toolbarClose()">انصراف</button><button class="primary" onclick="createPreviewDevice()">ایجاد</button></div>',480)}
function createPreviewDevice(){const id=String(document.getElementById('newDeviceId')?.value||'').trim(),type=document.getElementById('newDeviceType')?.value||'pc',cls=document.getElementById('newDeviceClass')?.value||'normal';if(!id||getDeviceById(id)){showToast('شناسه دستگاه خالی یا تکراری است');return}const d={id:id,type:type,state:type==='pc'?'Idle':'Ready',customer:'',session:type==='pc'?'—':type==='ps'?'PS5':'Table',remaining:'—',amount:'—',client:type==='pc'?'Running':'N/A',security:type==='pc'?'Normal':'N/A'};if(type==='pc')pcs.push(d);else if(type==='ps')ps.push(d);else fs.push(d);deviceTariffClass[id]=cls;persistAppState('device-create');toolbarClose();openDeviceManager()}
function openGameManager(){
  const activeCount=previewGames.filter(function(g){return g.active}).length,inactiveCount=previewGames.length-activeCount;
  const rows=previewGames.map(function(g){
    const gid=escapeHtml(g.id),name=escapeHtml(g.name),cat=escapeHtml(g.category);
    return '<div class="toolbar-row" style="grid-template-columns:70px minmax(180px,1fr) 130px 110px"><span>'+gid+'</span><span><b>'+name+'</b></span><span>'+cat+'</span><span><button class="mini-action '+(g.active?'is-active':'is-inactive')+'" onclick="togglePreviewGame(\''+gid+'\')">'+(g.active?'فعال':'غیرفعال')+'</button></span></div>'
  }).join('')||'<div class="toolbar-empty">هنوز بازی‌ای ثبت نشده است.</div>';
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page wide-page"><button class="close" aria-label="بستن" onclick="closeDetail()">×</button><div class="head"><div><div class="eyebrow">Game catalog</div><h2>بازی‌ها</h2><p class="toolbar-sub">کتابخانه بازی‌های فعال برای نمایش و مدیریت اپراتور.</p></div><div class="toolbar-actions"><button onclick="openSettings()">تنظیمات</button><button class="primary" onclick="openCreateGame()">＋ بازی جدید</button></div></div><div class="report-stat-grid"><div class="status-card"><span>کل بازی‌ها</span><strong>'+previewGames.length+'</strong></div><div class="status-card success"><span>فعال</span><strong>'+activeCount+'</strong></div><div class="status-card muted"><span>غیرفعال</span><strong>'+inactiveCount+'</strong></div></div><div class="toolbar-section-title"><strong>فهرست بازی‌ها</strong><span>تغییر وضعیت بدون خروج از پنجره</span></div><div class="toolbar-table"><div class="toolbar-row toolbar-head" style="grid-template-columns:70px minmax(180px,1fr) 130px 110px"><span>شناسه</span><span>بازی</span><span>دسته</span><span>وضعیت</span></div>'+rows+'</div></div></div>';
  setTimeout(decorateDialog,0)
}

function togglePreviewGame(id){const g=previewGames.find(function(x){return x.id===id});if(g){g.active=!g.active;persistAppState('game-toggle');openGameManager()}}
function openCreateGame(){toolbarModal('بازی جدید','<div class="grid2"><div><small>نام</small><input id="newGameName" class="toolbar-input" value="Apex Legends"></div><div><small>دسته</small><input id="newGameCategory" class="toolbar-input" value="Steam"></div></div><div class="actions"><button onclick="toolbarClose()">انصراف</button><button class="primary" onclick="createPreviewGame()">ذخیره</button></div>',450)}
function createPreviewGame(){const name=document.getElementById('newGameName')?.value.trim();if(!name){showToast('نام بازی الزامی است');return}previewGames.push({id:'G'+String(previewGames.length+1).padStart(2,'0'),name:name,category:document.getElementById('newGameCategory')?.value||'Other',active:true});persistAppState('game-create');toolbarClose();openGameManager()}
function openReports(){
  const active=previewCustomers.reduce(function(n,cc){return n+(cc.activeSessions?.length||0)},0);
  const wallet=previewCustomers.reduce(function(n,cc){return n+Number(cc.balance||0)+Number(cc.freeCredit||0)},0);
  const debt=previewCustomers.reduce(function(n,cc){return n+Number(cc.debt||0)},0);
  const revenue=previewPayments.reduce(function(n,p){return n+Number(p.amount||0)},0);
  const vip=previewCustomers.filter(function(cc){return cc.vipActive}).length;
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page wide-page"><button class="close" onclick="closeDetail()">×</button><div class="head"><div><div class="eyebrow">Reports</div><h2>آمار و وضعیت شعبه</h2><p class="toolbar-sub">نمایش سریع وضعیت مالی، مشتری و Sessionهای Preview.</p></div><div class="toolbar-actions"><button onclick="openPayments()">پرداختی‌ها</button><button onclick="openCustomerManager()">مشتریان</button><button class="primary" onclick="openBackup()">پشتیبان</button></div></div><div class="report-stat-grid"><div class="status-card success"><span>پرداخت ثبت‌شده</span><strong>'+revenue.toLocaleString()+' تومان</strong><small>'+previewPayments.length+' تراکنش</small></div><div class="status-card"><span>اعتبار و رایگان</span><strong>'+wallet.toLocaleString()+' تومان</strong><small>موجودی مشتریان</small></div><div class="status-card danger"><span>بدهی</span><strong>'+debt.toLocaleString()+' تومان</strong><small>جمع بدهی جاری</small></div><div class="status-card vip"><span>VIP فعال</span><strong>'+vip+'</strong><small>از '+previewCustomers.length+' مشتری</small></div></div><div class="report-grid-2"><div class="toolbar-section-card"><div class="toolbar-section-title"><strong>وضعیت عملیات</strong><span>Live Preview</span></div><div class="metric-list"><div><span>Session فعال</span><b>'+active+'</b></div><div><span>مشتری</span><b>'+previewCustomers.length+'</b></div><div><span>اتصال همزمان</span><b>'+previewCustomers.reduce(function(n,c){return n+Number(c.activeSessions?.length||0)},0)+'</b></div></div></div><div class="toolbar-section-card"><div class="toolbar-section-title"><strong>کنترل سریع</strong><span>ابزار اپراتور</span></div><div class="quick-action-grid"><button onclick="openPayments()">پرداختی‌ها</button><button onclick="openCustomerManager()">مدیریت مشتریان</button><button onclick="openDeviceManager()">دستگاه‌ها</button><button onclick="openSettings()">تنظیمات</button></div></div></div><div class="detail-alert">این صفحه Preview است؛ اعداد نمایشی‌اند و در نسخه تولیدی باید از وضعیت تأییدشده Server خوانده شوند.</div></div></div>'
}

function openPayments(){
  const total=previewPayments.reduce(function(n,p){return n+Number(p.amount||0)},0);
  const cash=previewPayments.filter(function(p){return String(p.type).includes('نقدی')}).reduce(function(n,p){return n+Number(p.amount||0)},0);
  const card=previewPayments.filter(function(p){return String(p.type).includes('کارت')}).reduce(function(n,p){return n+Number(p.amount||0)},0);
  const rows=previewPayments.map(function(p){return '<div class="toolbar-row" style="grid-template-columns:105px 95px minmax(220px,1fr) 110px 130px"><span>'+escapeHtml(p.id)+'</span><span>'+escapeHtml(p.time)+'</span><span>'+escapeHtml(p.customer)+' • '+escapeHtml(p.note)+'</span><span>'+escapeHtml(p.type)+'</span><span>'+Number(p.amount||0).toLocaleString()+' تومان</span></div>'}).join('')||'<div class="toolbar-empty">هنوز پرداختی ثبت نشده است.</div>';
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page wide-page"><button class="close" aria-label="بستن" onclick="closeDetail()">×</button><div class="head"><div><div class="eyebrow">Payments</div><h2>پرداختی‌ها</h2><p class="toolbar-sub">فهرست پرداخت‌های ثبت‌شده در Preview و جمع مبالغ.</p></div><div class="toolbar-actions"><button onclick="openReports()">آمار</button><button class="primary" onclick="openChargeManager()">＋ ثبت پرداخت</button></div></div><div class="report-stat-grid"><div class="status-card success"><span>جمع پرداخت</span><strong>'+total.toLocaleString()+' تومان</strong></div><div class="status-card"><span>نقدی</span><strong>'+cash.toLocaleString()+' تومان</strong></div><div class="status-card"><span>کارت</span><strong>'+card.toLocaleString()+' تومان</strong></div><div class="status-card muted"><span>تعداد تراکنش</span><strong>'+previewPayments.length+'</strong></div></div><div class="toolbar-table"><div class="toolbar-row toolbar-head" style="grid-template-columns:105px 95px minmax(220px,1fr) 110px 130px"><span>شناسه</span><span>زمان</span><span>مشتری / شرح</span><span>روش</span><span>مبلغ</span></div>'+rows+'</div></div></div>';
  setTimeout(decorateDialog,0)
}

function runPreviewSelfTest(){
  const checks=[],add=function(name,ok,detail){checks.push({name:name,ok:!!ok,detail:detail})};
  add('مسیرهای اصلی UI',
    ['openCustomerManager','openAccountCenter','confirmAccountAction','openDeviceManager','openStaffManager','openBackup','openRecovery','openActivation','openUpdates','openSharedTimeLab','runPreviewSelfTest'].every(function(n){return typeof window[n]==='function'}),
    'Customer / Account / Device / Staff / Backup / Recovery / Activation / Update');
  const rn=Number(previewPricing.normal.pc||0),rv=Number(previewPricing.vip.pc||0);
  const tn=rn>0?Math.floor(100000/rn*3600):0,tv=rv>0?Math.floor(100000/rv*3600):0,tb=(rn+rv)>0?Math.floor(100000/(rn+rv)*3600):0;
  add('تعرفه‌ها معتبرند',rn>0&&rv>0,'PC عادی '+rn.toLocaleString()+' و VIP '+rv.toLocaleString()+' تومان/ساعت');
  add('Time Pool عادی',rn>0&&tn===Math.floor(100000/rn*3600),'۱۰۰٬۰۰۰ → '+formatSharedTime(tn));
  add('Time Pool VIP',rv>0&&tv===Math.floor(100000/rv*3600),'۱۰۰٬۰۰۰ → '+formatSharedTime(tv));
  add('Time Pool همزمان',rn>0&&rv>0&&tb===Math.floor(100000/(rn+rv)*3600),'۱۰۰٬۰۰۰ با نرخ ترکیبی '+(rn+rv).toLocaleString()+' → '+formatSharedTime(tb));
  const paid=100000,bonus=Math.round(paid*10/100),total=paid+bonus;
  add('قانون ۱۰٪ هدیه',paid===100000&&bonus===10000&&total===110000,'پرداخت ۱۰۰٬۰۰۰ • رایگان ۱۰٬۰۰۰ • ارزش کل ۱۱۰٬۰۰۰');
  add('Journal مالی',typeof appendOperationJournal==='function'&&typeof replayUnappliedOperations==='function'&&typeof commitAccountOperation==='function','ثبت عملیات → Snapshot → Replay');
  add('مشتری همزمان',!!previewCustomers.find(function(c){return c.id==='1010'&&Number(c.maxConcurrent||0)>=2}),'مشتری 1010 برای تست چند Session آماده است');
  add('توابع Legacy حذف شده‌اند',typeof window.submitHotkeyCharge==='undefined'&&typeof window.formatManualTime==='undefined','ارجاع اجرایی قدیمی وجود ندارد');
  const good=checks.filter(function(c){return c.ok}).length,bad=checks.length-good;
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page" style="max-width:850px"><button class="close" onclick="closeDetail()">×</button><div class="eyebrow">QA / Debugger</div><h2>گزارش Self-Test</h2><p class="toolbar-sub">این تست خود UI Preview و منطق داخلی آن را بررسی می‌کند؛ Production همچنان باید Server + SQLite را Source of Truth نگه دارد.</p><div class="account-list">'+checks.map(function(c){return '<div class="account-row"><div class="account-row-label"><strong>'+(c.ok?'✓ ':'✕ ')+c.name+'</strong><small>'+c.detail+'</small></div><span class="'+(c.ok?'notice':'notice danger')+'">'+(c.ok?'PASS':'FAIL')+'</span></div>'}).join('')+'</div><div class="detail-alert '+(bad?'danger':'')+'">نتیجه: '+good+'/'+checks.length+' موفق'+(bad?' • '+bad+' مورد نیازمند بررسی':' • همه تست‌های فعلی سبز هستند')+'</div><div class="actions"><button onclick="openSettings()">بازگشت به تنظیمات</button></div></div></div>';
}
function openSettings(){const hk=getGameNetHotkeys();document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page"><button class="close" onclick="closeDetail()">×</button><div class="head"><div><div class="eyebrow">System settings</div><h2>تنظیمات</h2><p class="toolbar-sub">تعرفه، میانبر، کلاس دستگاه و Time Pool مشترک.</p></div><div class="toolbar-actions"><button class="primary" onclick="openHotkeySettings()">میانبرها</button><button onclick="openSharedTimeLab()">آزمایش زمان</button><button onclick="runPreviewSelfTest()">Self-Test</button></div></div><div class="toolbar-grid"><div class="toolbar-card"><h3>PC عادی</h3><input id="rate_normal_pc" class="toolbar-input" type="number" value="'+previewPricing.normal.pc+'"><p>۱۰۰٬۰۰۰ = ۳۰ دقیقه در نمونه</p></div><div class="toolbar-card"><h3>PC VIP</h3><input id="rate_vip_pc" class="toolbar-input" type="number" value="'+previewPricing.vip.pc+'"><p>۱۰۰٬۰۰۰ = ۶۰ دقیقه در نمونه</p></div><div class="toolbar-card"><h3>Time Pool</h3><p>نرخ Sessionها با هم جمع می‌شود.</p><span class="rate-badge">فعال</span></div><div class="toolbar-card"><h3>PS عادی</h3><input id="rate_normal_ps" class="toolbar-input" type="number" value="'+previewPricing.normal.ps+'"></div><div class="toolbar-card"><h3>PS VIP</h3><input id="rate_vip_ps" class="toolbar-input" type="number" value="'+previewPricing.vip.ps+'"></div><div class="toolbar-card"><h3>Foosball</h3><input id="rate_normal_fs" class="toolbar-input" type="number" value="'+previewPricing.normal.fs+'"><input id="rate_vip_fs" class="toolbar-input" type="number" value="'+previewPricing.vip.fs+'" style="margin-top:5px"></div></div><div class="toolbar-actions"><button class="primary" onclick="savePricingConfig()">ذخیره تعرفه‌ها</button><button onclick="openDeviceManager()">تعرفه هر دستگاه</button><button onclick="openCustomerManager()">مشتریان</button></div><div class="lab-result"><b>ذخیره فوری:</b> هر عملیات مالی در همین لحظه در Snapshot و ژورنال عملیات ثبت می‌شود؛ قطع برق بعد از ثبت عملیات نباید تراکنش ثبت‌شده را از بین ببرد.<br><b>میانبر:</b> '+hk.openCustomer+' مشتری • '+hk.chargeCustomer+' شارژ • '+hk.deductCustomer+' کسر • '+hk.debtCustomer+' بدهی • '+hk.discountCustomer+' هدیه • Enter تأیید</div></div></div>'}
function openSharedTimeLab(){const opts=previewCustomers.map(function(cc){return '<option value="'+cc.id+'">'+cc.id+' • '+cc.name+'</option>'}).join(''),dev=[...pcs,...ps,...fs].map(function(d){return '<option value="'+d.id+'">'+d.id+' • '+(getDeviceTariff(d.id)==='vip'?'VIP':'عادی')+' • '+getDeviceRate(d.id).toLocaleString()+' تومان/ساعت</option>'}).join('');document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page"><button class="close" onclick="closeDetail()">×</button><div class="eyebrow">Shared Time Pool</div><h2>آزمایش زمان همزمان</h2><p class="toolbar-sub">در مثال پیش‌فرض: ۱۰۰٬۰۰۰ عادی = ۳۰ دقیقه؛ VIP = ۶۰ دقیقه؛ هر دو همزمان = ۲۰ دقیقه.</p><div class="toolbar-grid"><div class="toolbar-card"><h3>دستگاه اول</h3><select id="labDevice1" class="toolbar-select">'+dev+'</select></div><div class="toolbar-card"><h3>دستگاه دوم</h3><select id="labDevice2" class="toolbar-select"><option value="">بدون دستگاه دوم</option>'+dev+'</select></div><div class="toolbar-card"><h3>موجودی</h3><input id="labBalance" class="toolbar-input" type="number" value="100000"></div></div><div id="sharedLabResult" class="lab-result"></div><div class="actions"><button onclick="openSettings()">بازگشت</button><button class="primary" onclick="applySharedLab()">اعمال Sessionها</button></div></div></div>';['labDevice1','labDevice2','labBalance'].forEach(function(id){document.getElementById(id)?.addEventListener('change',updateSharedLab);document.getElementById(id)?.addEventListener('input',updateSharedLab)});updateSharedLab()}
function updateSharedLab(){const d1=getDeviceById(document.getElementById('labDevice1')?.value),d2=getDeviceById(document.getElementById('labDevice2')?.value),b=Math.max(0,Number(document.getElementById('labBalance')?.value||0)),r1=d1?getDeviceRate(d1.id):0,r2=d2?getDeviceRate(d2.id):0,total=r1+r2,one=r1?Math.floor(b/r1*3600):0,two=total?Math.floor(b/total*3600):0,el=document.getElementById('sharedLabResult');if(el)el.innerHTML='<div class="lab-lines"><div><span>نرخ اول</span><strong>'+r1.toLocaleString()+' تومان/ساعت</strong></div><div><span>نرخ دوم</span><strong>'+r2.toLocaleString()+' تومان/ساعت</strong></div><div><span>زمان مشترک</span><strong>'+formatSharedTime(two)+'</strong></div></div><div class="detail-alert">نرخ ترکیبی '+total.toLocaleString()+' تومان/ساعت • فقط اول '+formatSharedTime(one)+' • هر دو '+formatSharedTime(two)+'</div>'}
function applySharedLab(){const d1=document.getElementById('labDevice1')?.value,d2=document.getElementById('labDevice2')?.value,cc=previewCustomers.find(function(x){return x.id==='1010'})||previewCustomers[0];if(!cc||!d1)return;cc.activeSessions.slice().forEach(function(s){removeCustomerSession(cc.id,s.deviceId)});cc.activeSessions=[];cc.balance=Math.max(0,Number(document.getElementById('labBalance')?.value||0));cc.freeCredit=0;cc.maxConcurrent=d2&&d2!==d1?2:1;startPreviewSession(cc.id,d1);if(d2&&d2!==d1)startPreviewSession(cc.id,d2);persistAppState('shared-lab');toolbarClose();openCustomerRecordPreview(cc.id)}
function openBackup(){
  const payload=JSON.stringify({schema:4,version:previewAppState.version,license:previewAppState.license,lastBackup:previewAppState.lastBackup,customers:previewCustomers,pcs:pcs,ps:ps,fs:fs,pricing:previewPricing,devices:deviceTariffClass,payments:previewPayments,operations:previewOperations,games:previewGames,staff:previewStaff,hotkeys:getGameNetHotkeys(),appliedOperationIds:_appliedOperationIds.slice(-300)},null,2);
  window._previewBackupPayload=payload;
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page medium-page"><button class="close" onclick="closeDetail()">×</button><div class="eyebrow">Backup & Recovery</div><h2>پشتیبان‌گیری</h2><p class="toolbar-sub">Snapshot کامل Preview شامل مشتریان، دستگاه‌ها، تعرفه‌ها، پرداخت‌ها، Sessionها و تنظیمات.</p><div class="report-stat-grid"><div class="status-card"><span>حجم Snapshot</span><strong>'+payload.length.toLocaleString()+'</strong><small>کاراکتر JSON</small></div><div class="status-card"><span>مشتری</span><strong>'+previewCustomers.length+'</strong></div><div class="status-card"><span>دستگاه</span><strong>'+([].concat(pcs,ps,fs).length)+'</strong></div><div class="status-card"><span>آخرین ذخیره</span><strong>'+(previewAppState.lastBackup||'—')+'</strong></div></div><div class="toolbar-section-card"><div class="toolbar-section-title"><strong>روش ذخیره</strong><span>هر دو گزینه محلی هستند</span></div><div class="quick-action-grid"><button onclick="savePreviewBackupLocal()">ذخیره Snapshot محلی</button><button class="primary" onclick="downloadPreviewBackup()">دانلود فایل JSON</button></div></div><div class="detail-alert">در نسخه تولیدی، موفقیت Backup فقط بعد از تأیید ذخیره پایدار گزارش می‌شود.</div></div></div>'
}

function savePreviewBackupLocal(){localStorage.setItem('gamenet_preview_backup',window._previewBackupPayload||'{}');previewAppState.lastBackup=new Date().toLocaleString('fa-IR');persistAppState('backup');showToast('Snapshot ذخیره شد')}
function downloadPreviewBackup(){const blob=new Blob([window._previewBackupPayload||'{}'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gamenet-preview-backup.json';a.click();URL.revokeObjectURL(a.href)}
function openRecovery(){
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page medium-page"><button class="close" onclick="closeDetail()">×</button><div class="eyebrow">Backup & Recovery</div><h2>بازیابی</h2><p class="toolbar-sub">Snapshot قبلی را انتخاب کن یا Backup محلی Preview را برگردان.</p><div class="file-picker"><div class="file-picker-icon">↻</div><div><strong>انتخاب فایل Backup</strong><small>JSON • Snapshot نسخه Preview</small></div><input id="recoveryFile" type="file" accept=".json,application/json"></div><div class="toolbar-actions recovery-actions"><button onclick="restoreLocalBackup()">بازیابی Snapshot محلی</button><button class="primary" onclick="restoreSelectedBackup()">خواندن و بازیابی فایل</button></div><div id="recoveryResult" class="detail-alert">هنوز فایلی انتخاب نشده است.</div></div></div>';
  const file=document.getElementById('recoveryFile');if(file)file.addEventListener('change',function(){const el=document.getElementById('recoveryResult');if(el)el.textContent=this.files?.[0]?'فایل «'+this.files[0].name+'» انتخاب شد.':'هنوز فایلی انتخاب نشده است.'})
}

function restoreLocalBackup(){const raw=localStorage.getItem('gamenet_preview_backup');if(!raw){showToast('Snapshot محلی وجود ندارد');return}try{restoreBackupObject(JSON.parse(raw))}catch(e){showToast('Snapshot خراب است')}}
function restoreSelectedBackup(){const file=document.getElementById('recoveryFile')?.files?.[0];if(!file){showToast('فایل را انتخاب کن');return}const fr=new FileReader();fr.onload=function(){try{restoreBackupObject(JSON.parse(fr.result))}catch(e){showToast('JSON نامعتبر است')}};fr.readAsText(file)}
function restoreBackupObject(obj){if(!obj||typeof obj!=='object'){showToast('Backup نامعتبر است');return}if(obj?.pricing){Object.assign(previewPricing.normal,obj.pricing.normal||{});Object.assign(previewPricing.vip,obj.pricing.vip||{})}if(Array.isArray(obj?.customers)){previewCustomers.splice(0,previewCustomers.length,...obj.customers);previewCustomers.forEach(function(cc){if(!Array.isArray(cc.activeSessions))cc.activeSessions=[]})}if(Array.isArray(obj?.pcs))pcs.splice(0,pcs.length,...obj.pcs);if(Array.isArray(obj?.ps))ps.splice(0,ps.length,...obj.ps);if(Array.isArray(obj?.fs))fs.splice(0,fs.length,...obj.fs);if(obj?.devices){Object.keys(deviceTariffClass).forEach(function(k){delete deviceTariffClass[k]});Object.assign(deviceTariffClass,obj.devices)}if(Array.isArray(obj?.payments))previewPayments.splice(0,previewPayments.length,...obj.payments);if(Array.isArray(obj?.operations))previewOperations.splice(0,previewOperations.length,...obj.operations);if(Array.isArray(obj?.games))previewGames.splice(0,previewGames.length,...obj.games);if(Array.isArray(obj?.staff)){previewStaff.splice(0,previewStaff.length,...obj.staff);previewStaff.forEach(function(x){if(!Array.isArray(x.permissions))x.permissions=x.role==='Owner'?previewPermissions.map(function(p){return p[0]}):['sessions'];if(!Array.isArray(x.customerPermissions))x.customerPermissions=x.customerProfile==='Full'?previewCustomerPermissions.map(function(p){return p[0]}):['identity']})}if(Array.isArray(obj?.appliedOperationIds))_appliedOperationIds=obj.appliedOperationIds.slice(-300);if(obj?.license)previewAppState.license=obj.license;if(obj?.version)previewAppState.version=obj.version;if(obj?.lastBackup)previewAppState.lastBackup=obj.lastBackup;if(obj?.hotkeys)saveGameNetHotkeys(obj.hotkeys);previewCustomers.forEach(function(cc){if(typeof cc.freeCredit!=='number')cc.freeCredit=0;if(typeof cc.maxConcurrent!=='number')cc.maxConcurrent=1;if(!Array.isArray(cc.activeSessions))cc.activeSessions=[]});persistAppState('backup-restore');closeDetail();render();showToast('Backup بازیابی شد و ذخیره شد')}
function openActivation(){
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page medium-page"><button class="close" onclick="closeDetail()">×</button><div class="eyebrow">License</div><h2>فعال‌سازی</h2><p class="toolbar-sub">کد مجوز Preview را وارد کن تا وضعیت فعال‌سازی در Demo ثبت شود.</p><div class="license-card"><div><span>وضعیت فعلی</span><strong>'+escapeHtml(previewAppState.license||'DEMO-LOCAL')+'</strong></div><span class="license-state">'+(String(previewAppState.license||'').startsWith('DEMO')?'نسخه آزمایشی':'فعال‌شده')+'</span></div><label class="field-label">کد فعال‌سازی<input id="licenseKey" class="toolbar-input" placeholder="مثلاً DEMO-ABC123" autocomplete="off"></label><div class="toolbar-actions"><button onclick="closeDetail()">انصراف</button><button class="primary" onclick="activatePreviewLicense()">فعال‌سازی</button></div><div class="detail-alert">این صفحه فقط برای Preview است و هیچ مجوز واقعی را صادر یا اعتبارسنجی نمی‌کند.</div></div></div>'
}

function activatePreviewLicense(){const key=String(document.getElementById('licenseKey')?.value||'').trim();if(key.length<6){showToast('کد فعال‌سازی نامعتبر است');return}recordCustomerEvent({type:'license-activation',label:'فعال‌سازی Preview'});previewAppState.license=key;persistAppState('activation');toolbarClose();showToast('فعال‌سازی انجام شد')}
function openUpdates(){
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page medium-page"><button class="close" onclick="closeDetail()">×</button><div class="eyebrow">Updates</div><h2>بروزرسانی</h2><p class="toolbar-sub">وضعیت نسخه و بررسی Update در محیط Preview.</p><div class="license-card"><div><span>نسخه فعلی</span><strong>'+escapeHtml(previewAppState.version)+'</strong></div><span class="license-state success">Preview</span></div><div class="toolbar-section-card"><div class="toolbar-section-title"><strong>بررسی بروزرسانی</strong><span>بررسی دستی</span></div><div id="updateResult" class="update-result">هنوز بررسی انجام نشده است.</div><div class="toolbar-actions"><button class="primary" onclick="checkPreviewUpdate()">بررسی دوباره</button><button onclick="openSettings()">تنظیمات</button></div></div><div class="detail-alert">نسخه تولیدی باید Update را از کانال امن و با کنترل نسخه و rollback انجام دهد؛ این صفحه فعلاً فقط Preview را شبیه‌سازی می‌کند.</div></div></div>'
}

function checkPreviewUpdate(){const el=document.getElementById('updateResult');if(el)el.textContent='بررسی شد: نسخه تستی فعلی به‌روز است.';showToast('وضعیت بروزرسانی بررسی شد')}
function openTariff(){
  const cls=selectedTariffClass,r=previewPricing[cls][tariffType];
  const tabs=['pc','ps','fs'].map(function(t){return '<button class="'+(tariffType===t?'sel':'')+'" onclick="setTariff(\''+t+'\')">'+t.toUpperCase()+'</button>'}).join('');
  const classes='<button class="'+(cls==='normal'?'sel':'')+'" onclick="setTariffClass(\'normal\')">عادی</button><button class="'+(cls==='vip'?'sel':'')+'" onclick="setTariffClass(\'vip\')">VIP</button>';
  document.getElementById('detail').innerHTML='<div class="detail"><div class="toolbar-page medium-page tariff-page"><button class="close" onclick="closeDetail()">×</button><div class="eyebrow">Pricing / Tariff</div><div class="head"><div><h2>تعرفه دستگاه</h2><p class="toolbar-sub">نرخ هر دستگاه را برای کلاس عادی یا VIP تنظیم و نتیجه را قبل از ذخیره محاسبه کن.</p></div><span class="rate-badge">'+(cls==='vip'?'VIP':'عادی')+'</span></div><div class="toolbar-section-title"><strong>کلاس تعرفه</strong><span>انتخاب سطح قیمت</span></div><div class="tariffTabs">'+classes+'</div><div class="toolbar-section-title"><strong>نوع منبع</strong><span>PC / PS / Foosball</span></div><div class="tariffTabs">'+tabs+'</div><div class="tariffGrid"><label>قیمت هر ساعت<input id="rate" type="number" min="0" step="1000" value="'+r+'" oninput="updateTariff()"></label><label>مبلغ تستی<input id="amount" type="number" min="0" step="1000" value="100000" oninput="updateTariff()"></label></div><div class="tariffResult"><div><small>زمان قابل خرید</small><b id="calcTime">'+formatRateTime(r,100000)+'</b></div><div><small>نرخ فعلی</small><b>'+r.toLocaleString()+' تومان/ساعت</b></div></div><div class="detail-alert">مثال پایه: ۱۰۰٬۰۰۰ تومان روی PC عادی با نرخ ۲۰۰٬۰۰۰ تومان/ساعت = ۳۰ دقیقه. روی VIP با نرخ ۱۰۰٬۰۰۰ = ۶۰ دقیقه. Sessionهای همزمان نرخ‌ها را جمع می‌کنند.</div><div class="toolbar-actions tariff-footer"><button onclick="openSettings()">تنظیمات</button><button onclick="closeDetail()">بستن</button><button class="primary" onclick="saveTariffFromModal()">ذخیره تعرفه</button></div></div></div>';
}

function setTariff(t){tariffType=t;openTariff()}
function setTariffClass(v){selectedTariffClass=v==='vip'?'vip':'normal';openTariff()}
function updateTariff(){const r=Number(document.getElementById('rate')?.value||0),a=Number(document.getElementById('amount')?.value||0),el=document.getElementById('calcTime');if(el)el.textContent=formatRateTime(r,a)}
function saveTariffFromModal(){previewPricing[selectedTariffClass][tariffType]=Math.max(0,Number(document.getElementById('rate')?.value||0));persistAppState('tariff');showToast('تعرفه ذخیره شد');openTariff()}
function toolAction(name){const map={'مشتریان':function(){showPage('Customers');openCustomerManager()},'شارژ':openChargeManager,'دستگاه جدید':openCreateDevice,'بازی‌ها':openGameManager,'تعرفه':openTariff,'آمار':openReports,'پرداختی':openPayments,'ادمین‌ها':function(){showPage('Branches & Staff');openStaffManager()},'تنظیمات':openSettings,'پشتیبان':openBackup,'بازیابی':openRecovery,'فعال‌سازی':openActivation,'بروزرسانی':openUpdates};if(map[name])return map[name]();showPage(name)}
function manualTick(){consumeSharedWallets();_persistTick++;if(_persistTick%2===0)persistAppState('tick');[...ps,...fs].forEach(function(x){const owner=previewCustomers.find(function(cc){return cc.activeSessions.some(function(s){return s.deviceId===x.id})});if(owner)return;if(typeof x.remainingSeconds==='number'&&x.remainingSeconds>0){x.remainingSeconds--;const t=x.remainingSeconds;x.remaining=formatSharedTime(t);x.timeWarning=t<=600&&t>0;x.timeUp=t<=0;x.notice=x.timeUp?'TIME UP':x.timeWarning?'Ending soon':'Running';x.timerLabel=x.timeUp?'00:00':Math.ceil(t/60)+' min';if(x.timeUp)x.state='Time Up'}});render()}
